QuanLyBanHang_KutsuSneakers/QuanLyBanHang_KutsuSneakers/Controllers/BanHangController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QuanLyBanHang_KutsuSneakers.Models;
using PagedList;
using PagedList.Mvc;
namespace QuanLyBanHang_KutsuSneakers.Controllers
{
    public class BanHangController : Controller
    {
        // GET: BanHang
        dbQLBanHangDataContext data = new dbQLBanHangDataContext();
        private List<SANPHAM> LaySPmoi(int count)
        {
            return data.SANPHAMs.OrderByDescending(b => b.NGAYCAPNHAT).Take(count).ToList();
        }
        public ActionResult Search()
        {
            return PartialView();
        }
        public ActionResult Index(FormCollection fc)
        {
            string name = fc["search"];
            if (name != null && name != "")
            {
                var sanpham = data.SANPHAMs.Where(p => p.TENSP.ToUpper().Contains(name.ToUpper())).ToList();
                return View(sanpham);
            }
            else
            {
                var spm = LaySPmoi(9);
                return View(spm);
            }
        }
        private List<SANPHAM> LaySP()
        {
            return data.SANPHAMs.OrderByDescending(a => a.NGAYCAPNHAT).ToList();
        }
        public ActionResult SanPham(int ? page, FormCollection fc)
        {
            string name = fc["Search"];
            if (name != null && name != "")
            {
                int PageNum = (page ?? 1);
                int pageSize = 9;
                var sanpham = data.SANPHAMs.Where(p => p.TENSP.ToUpper().Contains(name.ToUpper())).ToPagedList(PageNum, pageSize);
                return View(sanpham.ToPagedList(PageNum, pageSize));
            }
            else
            {
                int pageSize = 9;
                int PageNum = (page ?? 1);
                var spm = LaySP();
                return View(spm.ToPagedList(PageNum, pageSize));
            }
           
        }
        public ActionResult NhanHieu()
        {
            var nhanhieu = from nh in data.NHANHIEUs select nh;
            return PartialView(nhanhieu);
        }
        public ActionResult SPtheoNhanHieu(int id, int ? page)
        {
            int pageSize = 9;
            int PageNum = (page ?? 1);
            var sptnh = from s in data.SANPHAMs where s.MANH==id select s;
            return View(sptnh.ToPagedList(PageNum, pageSize));
        }
        public ActionResult Details(int id)
        {
            var ctsp = from s in data.SANPHAMs where s.MASP == id select s;
            return View(ctsp.Single());
        }
        private List<SANPHAM> Related(int count)
        {
            return data.SANPHAMs.OrderByDescending(a => a.NGAYCAPNHAT).Take(count).ToList();
        }
        public ActionResult SPLienQuan()
        {
            var splq = Related(4);
            return View(splq);
        }
        public ActionResult Size(int id)
        {
            var ctsp = from s in data.CTSPs where s.MASP == id select s;
            return PartialView(ctsp);
        }
        public ActionResult ChinhSachHoTro()
        {
            return View();
        }
    }
}

QuanLyBanHang_KutsuSneakers/QuanLyBanHang_KutsuSneakers/Views/BanHang/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<style>
    .current {
        background-color: black;
        color: white;
        font-weight: 600;
        margin-left: 10px;
        margin-right: 10px;
        border: 2px solid #000;
        box-shadow: inherit;
        padding: 5px;
        padding-left: 10px;
        padding-right: 10px;
    }
    #tab-list .item{
       border-radius: 5px;
    }

</style>
<body>
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <section class="section" id="product">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="left-images">
                        <img src="~/San_Pham/@Model.ANHSP" alt="@Model.TENSP">
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="right-content">
                        <h4>@Model.TENSP</h4>
                        <span class="price">@String.Format("{0:0,0}", Model.DONGIA) VNĐ</span>
                        <ul class="stars">
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                            <li><i class="fa fa-star"></i></li>
                        </ul>
                        <span>@Model.MOTA</span>
                        <div class="quantity-content">
                            <div class="left-content">
                                <h6>Số lượng</h6>
                            </div>
                            <div class="right-content">
                                <div class="quantity buttons_added">
                                    <input type="button" value="-" class="minus"><input type="number" step="1" min="1" max="" name="quantity" value="1" title="Qty" class="input-text qty text" size="4" pattern="" inputmode=""><input type="button" value="+" class="plus">
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="pagination">
                                <ul id="tab-list">
                                    <li class="item">
                                        @Html.Action("Size", "BanHang")
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="total">
                            <div class="main-border-button"><a href="javascript: ThemGH('@Model.MASP', ' ')">Đặt mua</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    @Html.Action("SPLienQuan", "BanHang")
</body>
<script>
    var size = 39;
    function changeSize(Size) {
        size = Size;
    }
    let x = document.getElementsByClassName("submit");
    for (let i = 0; i < x.length; i++) {
        x[i].onclick = function () {
            if (this.style.color !== "white") {
                this.style.backgroundColor = "black";
                this.style.color = "white";
            }
            else {
                this.style.backgroundColor = "white";
                this.style.color = "black";
            }
        };
    }
    function ThemGH(MaSP, strURL) {
        location.href = "../../../GioHang/ThemGioHang?MaSP=" + MaSP + "&Size=" + size + "&strURL=" + strURL;
    }
    const otems = document.getElementsByClassName('item')

</script>

QuanLyBanHang_KutsuSneakers/QuanLyBanHang_KutsuSneakers/Views/BanHang/Index.cshtml
@model IEnumerable<QuanLyBanHang_KutsuSneakers.Models.SANPHAM>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<meta name="viewport" content="with=device-with, initial-scale=1.0" />

<body>
   
    <!-- ***** Main Banner Area Start ***** -->
    <div class="main-banner" id="top">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6">
                    <div class="left-content">
                        <div class="thumb">
                            <div class="inner-content">
                                <h4>We Are Kutsu Sneakers</h4>
                                <div class="main-border-button">
                                    <a href="#">Tìm hiểu thêm</a>
                                </div>
                            </div>
                            <img src="~/San_Pham/rigt_banner_1.jpg">
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="right-content">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="right-first-image">
                                    <div class="thumb">
                                        <div class="inner-content">
                                            <h4>Jordan</h4>
                                        </div>
                                        <div class="hover-content">
                                            <div class="inner">
                                                <h4>Jordan</h4>
                                                <p>Sản phẩm Jordan tại Kutsu Sneakers</p>
                                                <div class="main-border-button">
                                                    <a href="#">Tìm hiểu thêm</a>
                                                </div>
                                            </div>
                                        </div>
                                        <img src="~/San_Pham/left_banner_jordan.jpg" width="347" height="320">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="right-first-image">
                                    <div class="thumb">
                                        <div class="inner-content">
                                            <h4>Nike</h4>
                                        </div>
                                        <div class="hover-content">
                                            <div class="inner">
                                                <h4>Nike</h4>
                                                <p>Sản phẩm Nike tại Kutsu Sneakers.</p>
                                                <div class="main-border-button">
                                                    <a href="#">Tìm hiểu thêm</a>
                                                </div>
                                            </div>
                                        </div>
                                        <img src="~/San_Pham/left_banner_nike.jpg" width="347" height="320">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="right-first-image">
                                    <div class="thumb">
                                        <div class="inner-content">
                                            <h4>Adidas</h4>
                                        </div>
                                        <div class="hover-content">
                                            <div class="inner">
                                                <h4>Adidas</h4>
                                                <p>Sản phẩm Adidas tại Kutsu Sneakers.</p>
                                                <div class="main-border-button">
                                                    <a href="#">Tìm hiểu thêm</a>
                                                </div>
                                            </div>
                                        </div>
                                        <img src="~/San_Pham/left_banner_adidas.jpg" width="347" height="320">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="right-first-image">
                                    <div class="thumb">
                                        <div class="inner-content">
                                            <h4>Puma</h4>
                                        </div>
                                        <div class="hover-content">
                                            <div class="inner">
                                                <h4>Puma</h4>
                                                <p>Sản phẩm Puma tại Kutsu Sneakers.</p>
                                                <div class="main-border-button">
                                                    <a href="#">Tìm hiểu thêm</a>
                                                </div>
                                            </div>
                                        </div>
                                        <img src="~/San_Pham/left_banner_puma.jpg" width="347" height="320">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ***** Main Banner Area End ***** -->
    <!-- ***** New - in Start ******-->
    <section class="section" id="products">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="section-heading">
                        <h2>Sản phẩm nổi bật</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                @if (Model != null)
                {
                    foreach (var sp in Model)
                    {
                        <div class="col-lg-4">
                            <div class="item">
                                <div class="thumb">
                                    <div class="hover-content">
                                        <ul>
                                            <li><a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})"><i class="fa fa-eye"></i></a></li>
                                            <li><a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})"><i class="fa fa-star"></i></a></li>
                                            <li><a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})"><i class="fa fa-shopping-cart"></i></a></li>
                                        </ul>
                                    </div>
                                    <a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})">
                                        <img src="~/San_Pham/@sp.ANHSP" alt="@sp.TENSP">
                                    </a>
                                </div>
                                <div class="down-content">
                                    <h4>@sp.TENSP</h4>
                                    <span>@String.Format("{0:0,0}", sp.DONGIA) VNĐ</span>
                                    <ul class="stars">
                                        <li><i class="fa fa-star"></i></li>
                                        <li><i class="fa fa-star"></i></li>
                                        <li><i class="fa fa-star"></i></li>
                                        <li><i class="fa fa-star"></i></li>
                                        <li><i class="fa fa-star"></i></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
    </section>
    <!-- ***** New - in End ******-->
    <!-- ***** Explore Area Starts ***** -->
    <section class="section" id="explore">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="left-content">
                        <h2>Sản phẩm sắp ra mắt</h2>
                        <span>Phối màu khá giống Jordan 1 Retro AJKO Chicago nhưng được làm bằng chất da giống các đôi giày khác. Tuy nhiên, nhà phát hành lại lấy ý tưởng từ đôi Jordan 1 High Chicago lịch sử của hãng với tông màu đỏ, trắng. Mặc dù thế, với phối màu Heritage cho thấy rõ thương hiệu đang tôn vinh những di sản mà Jordan cũng như đôi Bulls đã làm trong lịch sử.</span>
                        <div class="quote">
                            <i class="fa fa-quote-left"></i><p>Ngày phát hành: 09/04/2022</p>
                        </div>
                        <p>Mô hình mà bạn nhìn thấy ở đây cho thấy rằng Air Jordan 6 này sẽ được trang bị lớp nền Pure Platinum với các lớp phủ màu trắng được kết hợp giữa da lộn, da nubuck và da thuộc. Thêm một số điểm tương phản cho đôi giày thể thao này là các điểm nhấn Mint Foam ở khóa ren, gót, đế giữa và đế có thương hiệu. </p>
                        <div class="main-border-button">
                            <a href="/BanHang/SanPham">Tìm hiểu thêm</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="right-content">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="leather">
                                    <h4>Jordan 1 High Heritage</h4>
                                    <span>Phiên bản giới hạn</span>
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="first-image">
                                    <img src="~/San_Pham/Jordan1_High_Heritage.jpg" height="255px">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="second-image">
                                    <img src="~/San_Pham/Air_Jordan_6_Tiffany_Blue.jpg" height="255px">
                                </div>
                            </div>
                            <div class="col-lg-6">
                                <div class="types">
                                    <h4>Jordan 6 WMNS Tiffany Blue</h4>
                                    <span>Chỉ 500 đôi trên toàn cầu</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Explore Area Ends ***** -->
</body>

QuanLyBanHang_KutsuSneakers/QuanLyBanHang_KutsuSneakers/Views/BanHang/NhanHieu.cshtml
@model IEnumerable<QuanLyBanHang_KutsuSneakers.Models.NHANHIEU>
<ul>
    <li>
        @foreach (var nh in Model)
        {
            <a href="@Url.Action("SPtheoNhanHieu", "BanHang", new { id = nh.MANH})">
                @nh.TENNH
            </a>
        }
    </li>
</ul>

QuanLyBanHang_KutsuSneakers/QuanLyBanHang_KutsuSneakers/Views/BanHang/SPLienQuan.cshtml
@model IEnumerable<QuanLyBanHang_KutsuSneakers.Models.SANPHAM>
@{
    ViewBag.Title = "SPLienQuan";
    Layout = null;
}
<style>
    h2{
        text-align:center;
    }
</style>
    <section class="section" id="men">
        <div class="container">
                    <div class="section-heading">
                        <h2>Sản phẩm liên quan</h2>
                    </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="men-item-carousel">
                        <div class="owl-men-item owl-carousel">
                            @if (Model != null)
                            {
                                foreach (var sp in Model)
                                {
                                    <div class="item">
                                        <div class="thumb">
                                            <div class="hover-content">
                                                <ul>
                                                    <li><a href="@Url.Action("Details", "BanHang", new { id = sp.MASP })"><i class="fa fa-eye"></i></a></li>
                                                    <li><a href="@Url.Action("Details", "BanHang", new { id = sp.MASP })"><i class="fa fa-star"></i></a></li>
                                                    <li><a href="@Url.Action("Details", "BanHang", new { id = sp.MASP })"><i class="fa fa-shopping-cart"></i></a></li>
                                                </ul>
                                            </div>
                                            <a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})">
                                                <img src="~/San_Pham/@sp.ANHSP" alt="@sp.TENSP">
                                            </a>
                                        </div>
                                        <div class="down-content">
                                            <h4>@sp.TENSP</h4>
                                            <span>@String.Format("{0:0,0}", sp.DONGIA) VNĐ</span>
                                            <ul class="stars">
                                                <li><i class="fa fa-star"></i></li>
                                                <li><i class="fa fa-star"></i></li>
                                                <li><i class="fa fa-star"></i></li>
                                                <li><i class="fa fa-star"></i></li>
                                                <li><i class="fa fa-star"></i></li>
                                            </ul>
                                        </div>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

QuanLyBanHang_KutsuSneakers/QuanLyBanHang_KutsuSneakers/Views/BanHang/SPtheoNhanHieu.cshtml
@using QuanLyBanHang_KutsuSneakers.Models
@using PagedList.Mvc;
@model PagedList.PagedList < SANPHAM >
@{
    ViewBag.Title = "SPtheoNhanHieu";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<!-- ***** New - in Start ******-->
<body>
    <section class="section" id="products">
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-heading">
                            <h2>Sản phẩm nổi bật</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                @if (Model != null)
                {
                    foreach (var sp in Model)
                    {
                        <div class="col-lg-4">
                            <div class="item">
                                <div class="thumb">
                                    <div class="hover-content">
                                        <ul>
                                            <li><a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})"><i class="fa fa-eye"></i></a></li>
                                            <li><a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})"><i class="fa fa-star"></i></a></li>
                                            <li><a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})"><i class="fa fa-shopping-cart"></i></a></li>
                                        </ul>
                                    </div>
                                    <a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})">
                                        <img src="~/San_Pham/@sp.ANHSP" alt="@sp.TENSP">
                                    </a>
                                </div>
                                <div class="down-content">
                                    <h4>@sp.TENSP</h4>
                                    <span>@String.Format("{0:0,0}", sp .DONGIA) VNĐ</span>
                                    <ul class="stars">
                                        <li><i class="fa fa-star"></i></li>
                                        <li><i class="fa fa-star"></i></li>
                                        <li><i class="fa fa-star"></i></li>
                                        <li><i class="fa fa-star"></i></li>
                                        <li><i class="fa fa-star"></i></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
        <div class="col-lg-12">
            <div class="pagination">
                <ul>
                    <li>
                        Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
                    </li>
                    <li>
                        @Html.PagedListPager(Model, page => Url.Action("SanPham", new { page = page }))
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <!-- ***** New - in End ******-->
</body>

QuanLyBanHang_KutsuSneakers/QuanLyBanHang_KutsuSneakers/Views/BanHang/SanPham.cshtml
@using QuanLyBanHang_KutsuSneakers.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SANPHAM>
@{
    ViewBag.Title = "SanPham";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
}
<style>
    .search-box {
       position:absolute;
       top:93%;
       left:71%;
       transform:translate(-50%,-50%);
       background:#2f3640;
       height:40px;
       border-radius:40px;
      
    }
        .search-box:hover > .search-txt {
            width: 360px;
            padding: 0 6px;
        }

        .search-box:hover > .search-btn {
            background: white;
        }
    .search-btn {
        color: #e84118;
        float: right;
        width: 40px;
        height: 40px;
        border-radius: 50%;
        background-color: #2f3640;
        display: flex;
        justify-content: center;
        align-items: center;
        transition: 0.4s;
    }

    .search-txt {
        border: none;
        background: none;
        outline: none;
        float: left;
        padding: 0;
        color: #FFF;
        font-size: 16px;
        transition: 0.4s;
        line-height: 40px;
        margin-left: 18px;
        width:0px;
    }




</style>
<!-- ***** New - in Start ******-->
<body>
    <link rel="stylesheet" type="text/css" href="~/css/Slidebar.css">
    <!-- ***** Main Banner Area Start ***** -->
    <!-- Slideshow container -->

    <div class="slideshow-container">

        <!-- Full-width images with number and caption text -->
        <div class="mySlides fade">
            <img src="~/San_Pham/banner-1.jpg" style="width:100%">
        </div>

        <div class="mySlides fade">
            <img src="~/San_Pham/banner-2.jpg" style="width:100%">
        </div>

        <div class="mySlides fade">
            <img src="~/San_Pham/banner-3.jpg" style="width:100%">
        </div>
    </div>
    <br>

    <!-- The dots/circles -->
    <div style="text-align:center">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
        <span class="dot" onclick="currentSlide(4)"></span>
    </div>
    <!-- ***** Main Banner Area End ***** -->
    @using (Html.BeginForm("SanPham", "BanHang"))
    {
    <div class="search-box">
            <input type="text" placeholder="Nhập để tìm kiếm..." name="Search" class="search-txt" />
            <button type="submit" class="search-btn"><i class="fa fa-search" id="icon-search"></i></button>
    </div>
    }
    <section class="section" id="products">
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="section-heading">
                            <h2>Sản phẩm mới nhất</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                @if (Model != null)
                {
                    foreach (var sp in Model)
                    {
                        <div class="col-lg-4">
                            <div class="item">
                                <div class="thumb">
                                    <div class="hover-content">
                                        <ul>
                                            <li><a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})"><i class="fa fa-eye"></i></a></li>
                                            <li><a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})"><i class="fa fa-star"></i></a></li>
                                            <li><a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})"><i class="fa fa-shopping-cart"></i></a></li>
                                        </ul>
                                    </div>
                                    <a href="@Url.Action("Details", "BanHang", new { id = sp.MASP})">
                                        <img src="~/San_Pham/@sp.ANHSP" alt="@sp.TENSP">
                                    </a>
                                </div>
                                <div class="down-content">
                                    <h4>@sp.TENSP</h4>
                                    <span>@String.Format("{0:0,0}", sp.DONGIA) VNĐ</span>
                                    <ul class="stars">
                                        <li><i class="fa fa-star"></i></li>
                                        <li><i class="fa fa-star"></i></li>
                                        <li><i class="fa fa-star"></i></li>
                                        <li><i class="fa fa-star"></i></li>
                                        <li><i class="fa fa-star"></i></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    }
                }
            </div>
        </div>
        <div class="col-lg-12">
            <div class="pagination">
                <ul>
                    <li>
                        Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount
                    </li>
                    <li>
                        @Html.PagedListPager(Model, page => Url.Action("SanPham", new { page = page }))
                    </li>
                </ul>
            </div>
        </div>
    </section>
    <!-- ***** New - in End ******-->
</body>
<script>
    let slideIndex = 0;
    showSlides();

    function showSlides() {
        let i;
        let slides = document.getElementsByClassName("mySlides");
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > slides.length) { slideIndex = 1 }
        slides[slideIndex - 1].style.display = "block";
        setTimeout(showSlides, 1500); // Change image every 2 seconds
    }
</script>